#!/usr/bin/env bash
set -u
set -e

MS_SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
MS_HTML_FILE=

# prints the help message
print_usage() {
  echo -e "
usage: mailer [<command>] [--help]
  \033[1m --to,-t l\033[0m    Set the receiver
  \033[1m --help, -h\033[0m   Print this help text and exit
"
}

temp_file() {
  mkdir -p "tmp/mailer/" && echo "/tmp/mailer/$(date +%s-%N).html"
}

MAIL_FROM=""
MAIL_TO=""
MAIL_SUBJECT=""
MAIL_HEADLINE=""
MAIL_FOOTER=""

MAIL_CONTENT=""
MAIL_CONTENT_FILE=""

MS_CONFIG="/etc/mailer/mailer.conf"
[[ -f "${MS_CONFIG}" ]] && source "${MS_CONFIG}"

MS_MAIL_TEMPLATE="/etc/mailer/mail.html"
[[ -f "${MS_MAIL_TEMPLATE}" ]] || (echo "Missing file ${MS_MAIL_TEMPLATE}" && exit 0)

while (($# > 0)); do
  opt="${1}"
  shift
  case $opt in
  --help | -h)
    print_usage
    exit 0
    ;;
  --to | -t)
    MAIL_TO="${1}"
    shift
    ;;
  --subject | -s)
    MAIL_SUBJECT="${1}"
    shift
    ;;
  --headline | -h)
    MAIL_HEADLINE="${1}"
    shift
    ;;
  --footer | -ft)
    MAIL_FOOTER="${1}"
    shift
    ;;
  --file)
    MAIL_CONTENT_FILE="${1}"
    shift
    ;;
  --text)
    MAIL_CONTENT="${1}"
    shift
    ;;
  *)
    die "Unknown command: '${opt}'.  Pass '--help' for a list of commands."
    ;;
  esac
done

MS_TEMP_MAIL_HTML_FILE="/tmp/mailer-$(date +%s-%N).html"

cat ${MS_MAIL_TEMPLATE} >> "${MS_TEMP_MAIL_HTML_FILE}"

# cat "${MS_SCRIPT_DIR}/templates/startup.html" >>"${MS_TEMP_MAIL_CONTENT_HTML_FILE}"
# sed -i "s/__DATE__/$(date '+%d.%m.%Y %T')/g" "${MS_TEMP_MAIL_CONTENT_HTML_FILE}"
# sed -i "s/__HOSTNAME__/$(hostname)/g" "${MS_TEMP_MAIL_CONTENT_HTML_FILE}"
# sed -i -e "/__CONTENT__/{r $MS_TEMP_MAIL_CONTENT_HTML_FILE" -e "d}" "${MS_TEMP_MAIL_HTML_FILE}"

if [[ "${MAIL_HEADLINE}" == "" ]]; then
  MAIL_HEADLINE="${MAIL_SUBJECT}"
fi

if [[ "${MAIL_FOOTER}" == "" ]]; then
  MAIL_FOOTER="$(hostname)"
fi

echo "MAIL_CONTENT_FILE: ${MAIL_CONTENT_FILE}"

if [[ ! "${MAIL_CONTENT}" == "" ]]; then
  sed -i "s/__CONTENT__/${MAIL_CONTENT}/g" "${MS_TEMP_MAIL_HTML_FILE}"
elif [[ ! "${MAIL_CONTENT_FILE}" == "" ]]; then
  TMP_MAIL_CONTENT=$(cat "$MAIL_CONTENT_FILE")
  TMP_MAIL_CONTENT=$(echo "${TMP_MAIL_CONTENT//$'\n'/<br />}")
  TMP_FILE="/tmp/mailer-2-$(date +%s-%N).html"
  echo "${TMP_MAIL_CONTENT}" > "${TMP_FILE}"
  sed -i -e "/__CONTENT__/{r $TMP_FILE" -e "d}" "${MS_TEMP_MAIL_HTML_FILE}"
  rm -rf "${TMP_FILE}"
fi

sed -i "s/__FROM__/${MAIL_FROM}/g" "${MS_TEMP_MAIL_HTML_FILE}"
sed -i "s/__TO__/${MAIL_TO}/g" "${MS_TEMP_MAIL_HTML_FILE}"
sed -i "s/__SUBJECT__/${MAIL_SUBJECT}/g" "${MS_TEMP_MAIL_HTML_FILE}"
sed -i "s/__HEADLINE__/${MAIL_HEADLINE}/g" "${MS_TEMP_MAIL_HTML_FILE}"
sed -i "s/__FOOTER__/${MAIL_FOOTER}/g" "${MS_TEMP_MAIL_HTML_FILE}"

/usr/sbin/sendmail -t <"${MS_TEMP_MAIL_HTML_FILE}"

rm -rf "${MS_TEMP_MAIL_HTML_FILE}"
